#!/bin/sh

die () {
  echo "$1" >/dev/stderr
  exit 1
}

hg status|grep "^\?" && die "Stray files found."
echo "not running unit tests, shame shame"
cd examples/
#python3 regression.py || die "Unit tests failed."
cd ..
ssh diveintomark.org "hg -R /home/mark/db/diveintopython3/ serve --stdio" &
hg push ssh://mark@diveintomark.org//home/mark/db/diveintopython3/
